language: objective-c
osx_image: xcode7.2
xcode_project: DocOMatKit.xcodeproj
xcode_scheme: DocOMatKit
xcode_sdk: iphonesimulator9.2 
install: gem install travis-xcodebuild
env:
  global:
    - IOS_PLATFORM_NAME='iPad Air 2'
script: travis-xcodebuild
